# Урок 5

# Линейные преобразования

__1. Найти собственные векторы и собственные значения для линейного оператора, заданного матрицей__

$$A=\begin{pmatrix}
-1 & -6\\ 
2 & 6
\end{pmatrix}.$$

Решим характеристическое уравнение оператора А, чтобы найти собственные значения $\lambda$:

$det(\textbf{A}-\lambda\textbf{I})=0,$

$\begin{vmatrix}
-1 - \lambda & -6\\ 
2 & 6 - \lambda
\end{vmatrix} = 0$,

$(-1 - \lambda) \cdot (6 - \lambda) = 0, \lambda^{2} - 5\lambda + 6 = 0$,

$\lambda_{1} = 2, \lambda_{2} = 3.$


Теперь найдем собственные векторы вида $\begin{pmatrix}
x_{1}\\ 
x_{2}
\end{pmatrix}$, подставив полученные собственные значения в выражение $\textbf{A}x=\lambda x$:

1)  $\lambda=2$:

$\begin{pmatrix}
-1 & -6\\ 
2 & 6
\end{pmatrix}
\begin{pmatrix}
x_{1}\\ 
x_{2}
\end{pmatrix}=
2
\begin{pmatrix}
x_{1}\\ 
x_{2}
\end{pmatrix},
$

$\begin{cases}
-x_{1}-6\cdot x_{2}= 2\cdot x_{1}, \\
2\cdot x_{1}+6\cdot x_{2}= 2\cdot x_{2},   
\end{cases}
\begin{cases}
3\cdot x_{1}+6\cdot x_{2}= 0, \\
2\cdot x_{1}+4\cdot x_{2}= 0,   
\end{cases}
$

$x_{1} = -2 \cdot x_{2}.$

Т.е. в случае $\lambda=2$ оператор А имеет бесконечное множество собственных векторов с координатамии, удовлетворяющим уравнению выше.



2)  $\lambda=3$:

$\begin{pmatrix}
-1 & -6\\ 
2 & 6
\end{pmatrix}
\begin{pmatrix}
x_{1}\\ 
x_{2}
\end{pmatrix}=
3
\begin{pmatrix}
x_{1}\\ 
x_{2}
\end{pmatrix},
$

$\begin{cases}
-x_{1}-6\cdot x_{2}= 3\cdot x_{1}, \\
2\cdot x_{1}+6\cdot x_{2}= 3\cdot x_{2},   
\end{cases}
\begin{cases}
4\cdot x_{1}+6\cdot x_{2}= 0, \\
2\cdot x_{1}+3\cdot x_{2}= 0,   
\end{cases}
$

$x_{1} = -1.5 \cdot x_{2}.$

Т.е. в случае $\lambda=3$ оператор А имеет бесконечное множество собственных векторов с координатамии, удовлетворяющим уравнению выше.

In [1]:
import numpy as np

a = np.array([[-1, -6], [2, 6]])
w, v = np.linalg.eig(a)
 
print(f'Матрица A:\n{a}\n')
print(f'Собственные значения:\n{w}\n')
print(f'Собственные векторы:\n{v}\n')

Матрица A:
[[-1 -6]
 [ 2  6]]

Собственные значения:
[2. 3.]

Собственные векторы:
[[-0.89442719  0.83205029]
 [ 0.4472136  -0.5547002 ]]



__2. Дан оператор поворота на 180 градусов, задаваемый матрицей__ 

$$A=\begin{pmatrix}
-1 & 0\\ 
0 & -1
\end{pmatrix}.$$

Показать, что __любой__ вектор является для него собственным.

$\begin{vmatrix}
-1 - \lambda & 0\\ 
0 & -1 - \lambda
\end{vmatrix} = 0, (-1 - \lambda)^{2} = 0, \lambda = -1.$

$\begin{pmatrix}
-1 & 0\\ 
0 & -1
\end{pmatrix}
\begin{pmatrix}
x_{1}\\ 
x_{2}
\end{pmatrix}=
-1
\begin{pmatrix}
x_{1}\\ 
x_{2}
\end{pmatrix},
$

$\begin{cases}
-x_{1}-0\cdot x_{2}= -x_{1}, \\
0\cdot x_{1}-\cdot x_{2}= -x_{2},   
\end{cases}
\begin{cases}
x_{1}=x_{1}, \\
x_{2}= x_{2},   
\end{cases}
$

Т.к. любые значения $x_{1}$ и $x_{2}$ являются решениями полученной системы уравнений, то любой вектор - собственный для оператора А.

In [2]:
a = np.array([[-1, 0], [0, -1]])
w, v = np.linalg.eig(a)
 
print(f'Матрица A:\n{a}\n')
print(f'Собственные значения:\n{w}\n')
print(f'Собственные векторы:\n{v}\n')

Матрица A:
[[-1  0]
 [ 0 -1]]

Собственные значения:
[-1. -1.]

Собственные векторы:
[[1. 0.]
 [0. 1.]]



__3. Пусть линейный оператор задан матрицей__

$$A=\begin{pmatrix}
1 & 1\\ 
-1 & 3
\end{pmatrix}.$$

__Установить, является ли вектор $x=(1,1)$ собственным вектором этого линейного оператора.__


$\begin{pmatrix}
1 & 1\\ 
-1 & 3
\end{pmatrix}
\begin{pmatrix}
1\\ 
1
\end{pmatrix}=
\lambda
\begin{pmatrix}
1\\ 
1
\end{pmatrix},
\begin{cases}
1 \cdot 1 + 1 \cdot 1 = \lambda, \\
-1 \cdot 1 + 3 \cdot 1= \lambda,   
\end{cases}
\begin{cases}
\lambda=2, \\
\lambda=2.   
\end{cases}
$

Т.к. $\lambda=2$, то вектор х является собственным вектором оператора А.

In [3]:
a = np.array([[1, 1], [-1, 3]])
w, v = np.linalg.eig(a)
 
print(f'Матрица A:\n{a}\n')
print(f'Собственные значения:\n{w}\n')

Матрица A:
[[ 1  1]
 [-1  3]]

Собственные значения:
[2.00000002 1.99999998]



__4. Пусть линейный оператор задан матрицей__

$$A=\begin{pmatrix} 0 & 3 & 0\\ 3 & 0 & 0\\ 0 & 0 & 3 \end{pmatrix}.$$

__Установить, является ли вектор $x=(3, -3, -4)$ собственным вектором этого линейного оператора.__

$\begin{pmatrix}
0 & 3 & 0\\
3 & 0 & 0\\
0 & 0 & 3
\end{pmatrix}
\begin{pmatrix}
3\\ 
-3\\
-4
\end{pmatrix}=
\lambda
\begin{pmatrix}
3\\ 
-3\\
-4
\end{pmatrix},
$

$
\begin{cases}
9 = 3\lambda, \\
-9 = -3\lambda, \\
-12 = -4\lambda.   
\end{cases}
$

Т.к. $\lambda=3$, то вектор х является собственным вектором оператора А.

In [4]:
a = np.array([[0, 3, 0], [3, 0, 0], [0, 0, 3]])
w, v = np.linalg.eig(a)
 
print(f'Матрица A:\n{a}\n')
print(f'Собственные значения:\n{w}\n')

Матрица A:
[[0 3 0]
 [3 0 0]
 [0 0 3]]

Собственные значения:
[ 3. -3.  3.]

