# Урок 4

# Матрицы и матричные операции. Часть 1

__1.__ Установить, какие произведения матриц $AB$ и $BA$ определены, и найти размерности полученных матриц:

   а) $A$ — матрица $4\times 2$, $B$ — матрица $4\times 2$; - __и АВ, и ВА - произведение невозможно, т.к. число строк А не равно числу столбцов В__
    
   б) $A$ — матрица $2\times 5$, $B$ — матрица $5\times 3$; - __АВ - произведение невозможно, ВА - размерность $5\times 5$__
    
   в) $A$ — матрица $8\times 3$, $B$ — матрица $3\times 8$; - __АВ - размерность $8\times 8$, ВА - размерность $3\times 3$__
    
   г) $A$ — квадратная матрица $4\times 4$, $B$ — квадратная матрица $4\times 4$ - __АВ и ВА - размерность $4\times 4$__
   
   <br>

__2.__ Найти сумму и произведение матриц $A=\begin{pmatrix}
1 & -2\\ 
3 & 0
\end{pmatrix}$ и $B=\begin{pmatrix}
4 & -1\\ 
0 & 5
\end{pmatrix}.$

$
A + B =\begin{pmatrix}
1 + 4 & -2 - 1\\ 
3 + 0 & 0 + 5
\end{pmatrix}
= \begin{pmatrix}
5 & -3\\ 
3 & 5
\end{pmatrix}
$

$
A \cdot B =\begin{pmatrix}
1 \cdot 4 - 2 \cdot 0 & -1 \cdot 1 - 2 \cdot 5\\ 
3 \cdot 4 + 0 \cdot 0 & -3 \cdot 1 + 0 \cdot 5
\end{pmatrix}
= \begin{pmatrix}
4 & -11\\ 
12 & -3
\end{pmatrix}
$

In [1]:
import numpy as np

A = np.array([[1, -2], [3, 0]])
B = np.array([[4, -1], [0, 5]])

print(f'A + B:\n{A + B}')
print(f'A * B:\n{np.dot(A, B)}')

A + B:
[[ 5 -3]
 [ 3  5]]
A * B:
[[  4 -11]
 [ 12  -3]]


__3.__ Из закономерностей сложения и умножения матриц на число можно сделать вывод, что матрицы одного размера образуют линейное пространство. Вычислить линейную комбинацию $3A-2B+4C$ для матриц $A=\begin{pmatrix}
1 & 7\\ 
3 & -6
\end{pmatrix}$, $B=\begin{pmatrix}
0 & 5\\ 
2 & -1
\end{pmatrix}$, $C=\begin{pmatrix}
2 & -4\\ 
1 & 1
\end{pmatrix}.$

$3A-2B+4C=\begin{pmatrix}
3 \cdot 1 -2 \cdot 0 + 4 \cdot 2 & 3 \cdot 7 - 2 \cdot 5 - 4 \cdot 4\\ 
3 \cdot 3 - 2 \cdot 2 + 4 \cdot 1 & -3 \cdot 6 + 2 \cdot 1 + 4 \cdot1
\end{pmatrix}=
\begin{pmatrix}
11 & -5\\ 
9 & -12
\end{pmatrix}
$

In [2]:
A = np.array([[1, 7], [3, -6]])
B = np.array([[0, 5], [2, -1]])
C = np.array([[2, -4], [1, 1]])

print(f'3A - 2B + 4C:\n{3*A -2*B + 4*C}')

3A - 2B + 4C:
[[ 11  -5]
 [  9 -12]]


__4.__ Дана матрица $A=\begin{pmatrix}
4 & 1\\ 
5 & -2\\ 
2 & 3
\end{pmatrix}$.
Вычислить $AA^{T}$ и $A^{T}A$.

$A^{T}=\begin{pmatrix}
4 & 5 & 2\\ 
1 & -2 & 3
\end{pmatrix}$

$A \cdot A^{T}=\begin{pmatrix}
4 \cdot 4 + 1 \cdot 1 & 4 \cdot 5 - 1 \cdot 2 & 4 \cdot 2 + 1 \cdot 3\\ 
5 \cdot 4 - 2 \cdot 1 & 5 \cdot 5 + 2 \cdot 2 & 5 \cdot 2 - 2 \cdot 3\\
2 \cdot 4 + 3 \cdot 1 & 2 \cdot 5 - 3 \cdot 2 & 2 \cdot 2 + 3 \cdot 3\\
\end{pmatrix}
=\begin{pmatrix}
17 & 18 & 11\\ 
18 & 29 & 4\\
11 & 4 & 13
\end{pmatrix}
$

$A^{T} \cdot A=\begin{pmatrix}
4 \cdot 4 + 5 \cdot 5 + 2 \cdot 2 & 4 \cdot 1 - 5 \cdot 2 + 2 \cdot 3\\ 
1 \cdot 4 - 2 \cdot 5 + 3 \cdot 2 & 1 \cdot 1 + 2 \cdot 2 + 3 \cdot 3
\end{pmatrix}
=\begin{pmatrix}
45 & 0\\ 
0 & 14\\
\end{pmatrix}
$

In [3]:
A = np.array([[4, 1], [5, -2], [2, 3]])
A_T = A.T

print(f'A_T:\n{A_T}\n')
print(f'A * A_T:\n{np.dot(A, A_T)}\n')
print(f'A_T * A:\n{np.dot(A_T, A)}\n')

A_T:
[[ 4  5  2]
 [ 1 -2  3]]

A * A_T:
[[17 18 11]
 [18 29  4]
 [11  4 13]]

A_T * A:
[[45  0]
 [ 0 14]]



# Урок 4

# Матрицы и матричные операции. Часть 2

__1.Вычислить определитель:__ 

   a)

$$
\begin{vmatrix}
sinx & -cosx\\ 
cosx & sinx
\end{vmatrix} = sinx^{2} + cosx^{2} = 1;
$$

   б)
    
$$
\begin{vmatrix}
4 & 2 & 3\\ 
0 & 5 & 1\\ 
0 & 0 & 9
\end{vmatrix} = 4 \cdot 5 \cdot 9 = 180;
$$
    
   в)

\begin{vmatrix}
1 & 2 & 3\\ 
4 & 5 & 6\\ 
7 & 8 & 9
\end{vmatrix}.

Сначала преобразуем вторую строчку, вычев из нее первую, умноженную на -4. Затем преобразуем третью строку, вычев первую, умноженную на -7. В результате строки 2 и 3 будут линейно зависимы, значит определитель = 0:

$$
\begin{vmatrix}
1 & 2 & 3\\ 
4 & 5 & 6\\ 
7 & 8 & 9
\end{vmatrix} =
\begin{vmatrix}
1 & 2 & 3\\ 
0 & -3 & -6\\ 
7 & 8 & 9
\end{vmatrix} =
\begin{vmatrix}
1 & 2 & 3\\ 
0 & -3 & -6\\ 
0 & -6 & -12
\end{vmatrix} = 0.
$$


In [4]:
import numpy as np

a = np.array([[4, 2, 3], [0, 5, 1], [0, 0, 9]])
print(f'Матрица:\n{a}')
print(f'Определитель:\n{np.linalg.det(a):.0f}\n')

b = np.array([[1, 2, 3], [4, 5, 6], [7, 8, 9]])
print(f'Матрица:\n{b}')
print(f'Определитель:\n{np.linalg.det(b):.0f}\n')

Матрица:
[[4 2 3]
 [0 5 1]
 [0 0 9]]
Определитель:
180

Матрица:
[[1 2 3]
 [4 5 6]
 [7 8 9]]
Определитель:
-0



__2. Определитель матрицы $A$ равен $4$. Найти:__

   а) $det(A^{2}) = det(A \cdot A) = det(A) \cdot det(A) = 4 \cdot 4 = 16$;
    
   б) $det(A^{T}) = det(A) = 4$;
    
   в) $det(2A) = det(A) \cdot 2^{n} = 4 \cdot 2^{n},$ где n - размерность матрицы .

In [5]:
c = np.array([[1, 2, 3, 1], [0, 4, 1, 1], [0, 0, 1, 1], [0, 0, 0, 1]])
print(f'Определитель A:\n{np.linalg.det(c):.0f}\n')
print(f'Определитель 2A:\n{np.linalg.det(2 * c):.0f}\n')

Определитель A:
4

Определитель 2A:
64



__3. Доказать, что матрица вырожденная:__  

$$\begin{pmatrix}
-2 & 7 & -3\\ 
4 & -14 & 6\\ 
-3 & 7 & 13
\end{pmatrix}$$

Видно, что второая строка - это удвоенная первая со знаком минус. Т.е. две строки матрицы линейно зависимы. По свойству определителей, определитель такой матрицы равен нулю.
Матрица называется вырожденной, если ее определитель равен нулю. Значит данная матрица - вырожденная.

__4. Найти ранг матрицы:__

   а)
$
\begin{pmatrix}
1 & 2 & 3\\ 
1 & 1 & 1\\ 
2 & 3 & 4
\end{pmatrix} =>
\begin{pmatrix}
1 & 2 & 3\\ 
1 & 1 & 1
\end{pmatrix}
$ => ранг 2 (третья строка = сумме первых двух, ее можно отбросить)

   б)
$
\begin{pmatrix}
0 & 0 & 2 & 1\\ 
0 & 0 & 2 & 2\\ 
0 & 0 & 4 & 3\\ 
2 & 3 & 5 & 6
\end{pmatrix} =>
\begin{pmatrix}
0 & 0 & 2 & 1\\ 
0 & 0 & 2 & 2\\ 
2 & 3 & 5 & 6
\end{pmatrix}
$ => ранг 3 (третья строка = сумме первых двух, ее можно отбросить)

In [6]:
a = np.array([[1, 2, 3], [1, 1, 1], [2, 3, 4]])
b = np.array([[0, 0, 2, 1], [0, 0, 2, 2], [0, 0, 4, 3], [2, 3, 5, 6]])

print(f'Ранг матрицы A: {np.linalg.matrix_rank(a)}\n')
print(f'Ранг матрицы B: {np.linalg.matrix_rank(b)}\n')

Ранг матрицы A: 2

Ранг матрицы B: 3

